name: Java Build, Test and Package

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, closed]
  workflow_dispatch: {}

jobs:
  build-and-tests:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify

  build-and-package:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Publish to GitHub Packages Apache Maven
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-aws:
    needs: build-and-package
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up AWS CLI
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: xxxx #${{ secrets.AWS_ACCESS_KEY_ID}}
    #     aws-secret-access-key: xxxx #${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-2

    - name: Deploy to AWS Elastic Beanstalk
      run: echo "The deployment has been successful."
